### ISSUE TITLE
Premature EOF in OaImporter

### ISSUE THREAD

**Issue by lorenaqendro** [FutureCitiesCatapult/TomboloDigitalConnector#373]
### Description
When running one of the recipes that require the OaImporter data the following error is launched,

### Error log
```
java.lang.RuntimeException: java.io.IOException: Premature EOF
        at org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.readNext(FeatureJSON.java:750)
        at org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.hasNext(FeatureJSON.java:734)
        at uk.org.tombolo.importer.ons.OaImporter.importDatasource(OaImporter.java:67)
        at uk.org.tombolo.importer.AbstractImporter.importDatasource(AbstractImporter.java:104)
        at uk.org.tombolo.execution.DataExportEngine.importDatasource(DataExportEngine.java:96)
        at uk.org.tombolo.execution.DataExportEngine.execute(DataExportEngine.java:46)
        at uk.org.tombolo.DataExportRunner.run(DataExportRunner.java:45)
        at uk.org.tombolo.DataExportRunner.main(DataExportRunner.java:26)
Caused by: java.io.IOException: Premature EOF
        at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
        at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
        at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
        at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:98)
        at org.apache.commons.io.input.TeeInputStream.read(TeeInputStream.java:127)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.read1(BufferedReader.java:210)
        at java.io.BufferedReader.read(BufferedReader.java:286)
        at org.json.simple.parser.Yylex.zzRefill(Yylex.java:345)
        at org.json.simple.parser.Yylex.yylex(Yylex.java:541)
        at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:466)
        at org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.readNext(FeatureJSON.java:746)
        ... 7 more

```

**Comment by arya-hemanshu** [comment]
It looks like that 'geoportal.statistics.gov.uk' is closing the connection too soon. It worked for me twice but looks like only when the connection is strong.

To test that i picked 2 urls, one from 'OaImporter' and other from 'Londonairquality' and created two scripts one in java and one in python and in both the scripts connection for 'OaImporter' is closing abruptly. Below are both the scripts:

Java:

import java.io.*;
import java.net.URL;

public class TestClass {

    public static void main(String[] args) throws IOException {
        //it looks like the server is closing the connection too soon
        URL url = new URL("http://geoportal.statistics.gov.uk/datasets/da831f80764346889837c72508f046fa_2.geojson");

        //Uncomment this to see that the code is fine, as the same code is working fine with this url
//        URL url = new URL("http://api.erg.kcl.ac.uk/AirQuality/Annual/MonitoringObjective/GroupName=London/Year=2010/json");
        InputStream is = url.openStream();
        byte[] bytes = new byte[1024];
        try {
            while (is.read(bytes) != -1) {
                System.out.println(new String(bytes));
            }
        } catch (IOException e){ e.printStackTrace(); }
        is.close();
    }
}


Python:

from urllib.request import urlopen
import http

try:
    response = urlopen('http://geoportal.statistics.gov.uk/datasets/da831f80764346889837c72508f046fa_2.geojson')
    # response = urlopen('http://api.erg.kcl.ac.uk/AirQuality/Annual/MonitoringObjective/GroupName=London/Year=2010/json')
    print(response.read())
except http.client.IncompleteRead as i:
    print(i.partial)
    print('an exception has occurred')


Try running it by uncommenting the different urls.
