### ISSUE TITLE
runExport Example Fails in Windows

### ISSUE THREAD

**Issue by ShreejeetaMandal** [FutureCitiesCatapult/TomboloDigitalConnector#465]
### Versions

Please provide your platform details:

| Software | Information |
| :--- | :--- |
| Operating System| `Windows 10 Home` |
| OS Version| `10` |
| java -version | `1.8.0_144` | 
| psql --version | `9.6.3` |
| gradle --version | `4.5` |

Software versions in the [Let's start](/README.md#lets-start) section in the README.

### Description
As per the Windows Installation Guide, after successfully installing all the requirements and building the Digital Connector, we run the runExport command to test.
Tombolo throws a Configuration Exception - Unknown DatasourceId:trafficCounter.
Opened the reaggregate-traffic-count-to-la.json and there is no "DatasourceId:trafficCounter".
There is only "subjectType": "trafficCounter", "datasourceId": "trafficCounts", and "datasourceId": "localAuthority".

### Error log

```
gradle runExport -Precipe=src\main\resources\executions\examples\reaggregate-traffic-count-to-la-copy.json -Poutput=reaggregate-traffic-count-to-la_output.json
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :runExport
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2018-02-07 15:39:05.550 [main] WARN  n.s.e.config.ConfigurationFactory - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/C:/Users/Shree/.gradle/caches/modules-2/files-2.1/net.sf.ehcache/ehcache/2.10.3/cf74f9a4a049f181833b147a1d9aa62159c9d01d/ehcache-2.10.3.jar!/ehcache-failsafe.xml
2018-02-07 15:39:06.851 [main] INFO  uk.org.tombolo.AbstractRunner - Setting file download cache: /tmp
2018-02-07 15:39:07.036 [main] INFO  org.ehcache.core.EhcacheManager - Cache 'fields' created in EhcacheManager.
2018-02-07 15:39:07.367 [main] INFO  u.o.t.importer.AbstractImporter - Skipped importing uk.org.tombolo.importer.ons.OaImporter:localAuthority as this import has been completed previously
uk.org.tombolo.importer.ConfigurationException: Unknown DatasourceId:trafficCounter
        at uk.org.tombolo.importer.AbstractImporter.importDatasource(AbstractImporter.java:95)
        at uk.org.tombolo.importer.AbstractOaImporter.importDatasource(AbstractOaImporter.java:28)
        at uk.org.tombolo.execution.DataExportEngine.importDatasource(DataExportEngine.java:92)
        at uk.org.tombolo.execution.DataExportEngine.execute(DataExportEngine.java:47)
        at uk.org.tombolo.DataExportRunner.run(DataExportRunner.java:56)
        at uk.org.tombolo.DataExportRunner.main(DataExportRunner.java:32)
Exception in thread "main" java.lang.RuntimeException
        at uk.org.tombolo.DataExportRunner.run(DataExportRunner.java:59)
        at uk.org.tombolo.DataExportRunner.main(DataExportRunner.java:32)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runExport'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_144\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
3 actionable tasks: 1 executed, 2 up-to-date

```

**Comment by arya-hemanshu** [comment]
@ShreejeetaMandal thank you for raising the issue, it is known bug and we are working to fix it. Until this is fixed as a work around you could go to 
```
AbstractDFTImporter.java under src/main/java/uk/org/tombolo/importer/dft
extend the class from AbstractImporter rather from AbstractOaImporter

Replace:
public abstract class AbstractDFTImporter extends AbstractOaImporter 

With:
public abstract class AbstractDFTImporter extends AbstractImporter
```

**Comment by ShreejeetaMandal** [comment]
@arya-hemanshu Thanks!! I have implemented the change and ran it. It went further than before but I faced another error during Exporting. I thought it was because the output file created doesn't have write permission or the like but even after creating a new folder and directing the new file to that folder, the same error is thrown. the file is being created though.

The error is as follows, 
2018-02-07 16:28:10.595 [main] INFO  u.o.t.importer.AbstractImporter - Preparing to write a batch of 86916 timed values ...
2018-02-07 16:28:34.031 [main] INFO  u.o.t.importer.AbstractImporter - Total timed values written: 186918
2018-02-07 16:28:34.037 [main] INFO  u.o.t.importer.AbstractImporter - Imported 1889 subjects, 7556 fixed values and 186918 timedValues
2018-02-07 16:28:34.074 [main] INFO  u.o.t.execution.DataExportEngine - Exporting ...
java.lang.NullPointerException
        at uk.org.tombolo.core.utils.SubjectUtils.queryFromSubjectSpecification(SubjectUtils.java:165)
        at uk.org.tombolo.core.utils.SubjectUtils.lambda$getSubjectBySpecification$5(SubjectUtils.java:80)
        at uk.org.tombolo.core.utils.HibernateUtil.withSession(HibernateUtil.java:34)
        at uk.org.tombolo.core.utils.SubjectUtils.getSubjectBySpecification(SubjectUtils.java:79)
        at uk.org.tombolo.core.utils.SubjectUtils.getSubjectBySpecifications(SubjectUtils.java:87)
        at uk.org.tombolo.execution.DataExportEngine.execute(DataExportEngine.java:65)
        at uk.org.tombolo.DataExportRunner.run(DataExportRunner.java:56)
        at uk.org.tombolo.DataExportRunner.main(DataExportRunner.java:32)
Exception in thread "main" java.lang.RuntimeException
        at uk.org.tombolo.DataExportRunner.run(DataExportRunner.java:59)
        at uk.org.tombolo.DataExportRunner.main(DataExportRunner.java:32)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runExport'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_144\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 43s
3 actionable tasks: 2 executed, 1 up-to-date

**Comment by arya-hemanshu** [comment]
@ShreejeetaMandal  Please pull new master and once that is done make the above suggested change again.

**Comment by ShreejeetaMandal** [comment]
@arya-hemanshu Thank you so much!! The fix worked!

**Comment by ShreejeetaMandal** [comment]
Hi @lorenaqendro / @borkurdotnet ,
Should we add this work around in the Windows installation guide until we find the solution? Just a suggestion..

**Comment by lorenaqendro** [comment]
Closing as the bug fix is now in the master master branch.
